import pandas as pd, numpy as np
p = pd.read_csv('outputs/basin_precipitation.csv', index_col=0)
print('Shape:', p.shape)
print('Coverage:')
print(p.notna().sum())
print()
print('Head:')
print(p.head())
print()
print('Non-NaN mean:')
print(p.mean())
